{% set name = "pytest-mccabe" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 050a1f1c145202ea87f0c0ad7b529f088098040fe2eb8e5d797d36be86e0fa20

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - pytest-cache
    - pytest >=2.3.dev14
    - mccabe
  run:
    - python
    - setuptools
    - pytest-cache
    - pytest >=2.3.dev14
    - mccabe

test:
  commands:
    - py.test --mccabe -h

about:
  home: https://github.com/The-Compiler/pytest-mccabe
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: pytest plugin to run the mccabe code complexity checker.
  description: py.test plugin for checking cyclomatic complexity of python source with 'mccabe'.

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - visze
