{% set name = "pytest-mccabe" %}
{% set version = "1.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "02c9c1e9d02f0522d659809e1e7bf74e3e8fa7fb74eb55f177afb4701c8d9a4c" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - pytest-cache
    - pytest >=2.3.dev14
    - mccabe
  run:
    - python
    - setuptools
    - pytest-cache
    - pytest >=2.3.dev14
    - mccabe

test:
  commands:
    - py.test --mccabe -h

about:
  home: https://github.com/The-Compiler/pytest-mccabe
  license: MIT
  license_family: MIT
  summary: pytest plugin to run the mccabe code complexity checker.
  description: "py.test plugin for checking cyclomatic complexity of python source with 'mccabe'."

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - visze
