travis:
  secure:
    BINSTAR_TOKEN: hS/0JPyaHa9hx5ezQo0gmng9pb6SvO0LrAjDQtDuTG4ZsuP76qn+Lo4hhY0BB4tOKI60dCeaA2Xo+jlhP3wlNRVbKKUgsQLIf2ym3+mSWVz8VLN5XGpIdkOzmSK1XNUA+co54kspWPaIKLmuxplqb3uKMA2DbEbAc0FmwZ0piTO+tetawD72z1oKUQGYDphwB2MB5qrc2Ql8rkhzcIvhd3PT7eODxs3UGstmwC07l9hRNmY+8pthLPGihZs55uvaVwDXAzRj51nDhvJhMIjCPpURPkervz/oMp6w2Yz19494hDpuzArth6G9p3/AOeVynUiRziZ4BdroOYAwKhXX76NXfgF02+O8XqhJvAUDvVDSWkwq6uysYjq75XzDAmmqlc1hpgOW7O3xiITlFMiIPtq2lvf5gJPlLKFxGqHHyMQzKoqJIsdreQ+aLJ5CAzvLWkm8SRkUli4lWfBcI766F5+PeCa/5mguTI3V6teKlFSYXiymajsjuVTzcRDI1/cyjjP59opSNrg882hjc4aT9M5vZm841lKemSS9qQ/kpMkyhxWKL5ICSefcRHFc5LhdiuREWpoeSujFc3IkQfgS35w81vu+gc1xy5urCSF5PyrMRzVfDqXcl/0peXF/ZGarumRtccgK9Y9HTQhixFk80vZEJ1ef3dCbLdUfintEo/o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
