travis:
  secure:
    BINSTAR_TOKEN: uLuaiI0tV6OUL8C0Wv8hZHhfe7Mwu/HMFYUKbwoe5XJuUPDOaC7abgN48BxOGfpQc1h+/8aYF5EZzIevamNV3AEKqjEmvfnJFH3EiJvhzSuOqU4lugkffZGl45sZnO7IM+/GQ6jqFodZNLwWUMfsUeIktkg37XEutIAxdlOLWYolCXYHTjeD+aBk2muUpDc68CAWkpw0R0VWKyis+/uxw5WTec3h4Mvvmb+8DDgXtR7W6Ojjid4nqcElCJBwAKo41yu7AEw3hqd+bIthNflNHegTBu+OvMP7znWzYh/qSkowpSmhHPedOQoVKs3KInqWSOHnGwl4JTfyBZXcxU55xDUghyi6tzixsS9K7pxrbcqzGBbPo4jcishu9wUNnRgoZmO3/sXxEuj1OPJx7RxqMM+RqVypH2HtMrST1s7lLAQ5Uw7gTy/Nuz3Z/P9hdHEUNeqY0U9St8OSzEEr8uECPH9HGsWOV2HYq5rBtzippFrr2ignFuNmPmvl09MuTe3ScxIfm4BlxcWeWVOLr1C64BxPw97S1zwNO+vxIbpn5VyAIu/FgZZcoxUQRkDPy6XpqckV+iBuQY4RCMgIkS1MR8anLh9pKkgpRkYitJpuBKaFsEebkFZ1q+nPdkf3loy1bFK5XNPYMMXCSVZp5AW55M6xOXTZyb0r8+tF8lpqdgI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
